services:
  db:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - constructdb:/var/lib/postgresql
  construct:
    restart: always
    depends_on:
      - db
    ports:
      - 3004:3000
    env_file:
      - .env
    pull_policy: always
    image: ghcr.io/hackclub/construct:staging
networks: {}
volumes:
  constructdb: